### ISSUE TITLE
jwt valid time 정하기

### ISSUE THREAD

**Issue by KwonMinho** [Seongtaek-H/everyone-quest-backend#12]
jwt 유효시간을 몇 분으로 하는게 좋을까요?

**Comment by dudwns0921** [comment]
서비스 자체가 오래 시간을 써야 하는 구조가 아니라서 30분이 좋을 거 같습니다!

**Comment by KwonMinho** [comment]
아직 서비스에 별다른 요구사항 없기 때문에, 저도 30분이 적당한 거같습니다.

별다른 이견이 없으시면, 내일 이슈 닫겠습니다.
