### ISSUE TITLE
User Domain gradlew test 실패

### ISSUE THREAD

**Issue by jaeho9929** [Seongtaek-H/everyone-quest-backend#13]
# 재현과정
1. gradlew clean
2. gradlew test

# 발생커밋 
63c1eb0

# 참고자료
[test.zip](https://github.com/Seongtaek-H/everyone-quest-backend/files/8102078/test.zip)

**Comment by KwonMinho** [comment]
오늘 오후 7시쯤 한번 확인해보겠습니다.
죄송합니다.
