### ISSUE TITLE
일반 로그인 기능에 대한 테스트 코드 안되는 이슈 확인..

### ISSUE THREAD

**Issue by KwonMinho** [Seongtaek-H/everyone-quest-backend#15]
- 포스트맨에서 정상적으로 동작하나 테스트코드에서 자꾸 에러남..

**Comment by jaeho9929** [comment]
#13 과 같은 원인 때문인 것 같습니다.
intellij 에서는 기본적으로 아무런 옵션이 부여되지 않은 채 gradle task가 수행 되는거 같더군요.
환경을 확인 해 보니, 실행 시 환경은 다음과 같습니다.

1.  포스트맨에서 정상적으로 동작하는경우
- gradlew bootRun 명령어로 동작 -> 빌드환경 : dev, 런타임환경 dev
2. 테스트 코드 실행의 경우
- gradlew test 명령어로 동작 -> 빌드환경 : test, 런타임환경 dev -->test 로 동작 되어야 함.
- 현재 해결 방안 : gradlew test -Pprofile=test -> 빌드환경 : test, 런타임환경 test
